services:
  db:
    container_name: grex-db
    image: postgres
    env_file:
      - .env.dev
  server:
    container_name: grex-server
    build: .
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
